# Generated by Django 6.0.6 on 2026-06-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
